ingressClass:
  enabled: false
ports:
  traefik:
    # Override the default port to avoid conflicts with other services
    port: 9001
hostNetwork: true
deployment:
  dnsPolicy: ClusterFirstWithHostNet
securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  runAsNonRoot: false
  runAsUser: 0
