ingressClass:
  enabled: false
hostNetwork: true
deployment:
  dnsPolicy: ClusterFirstWithHostNet
securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  runAsNonRoot: false
  runAsUser: 0
