ingressClass:
  enabled: false
ports:
  # Override the default ports to avoid conflicts with other services
  traefik:
    port: 9001
  metrics:
    port: 9101
hostNetwork: true
deployment:
  dnsPolicy: ClusterFirstWithHostNet
securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  runAsNonRoot: false
  runAsUser: 0
